<?php

namespace AppBundle\Repository;

/**
 * BilanDiscipliaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BilanDiscipliaireRepository extends \Doctrine\ORM\EntityRepository
{
}
