<?php

namespace AppBundle\Repository;

/**
 * OffreEmploieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreEmploieRepository extends \Doctrine\ORM\EntityRepository
{
}
